title: "Joycelyn Ovalle"
description_top: "PhD | MPP"
affiliation: "The University of Texas at Austin"

show_downloads: false
google_analytics: ""

scholar_url: "https://scholar.google.com/citations?user=yehlXLQAAAAJ&hl=en"
orcid_url:   "https://orcid.org/YOUR-ORCID"
linkedin_url: "https://www.linkedin.com/in/ovallejoycelyn"

theme: jekyll-theme-dinky
plugins:
  - jekyll-seo-tag
